name: Deploy to EC2

on:
  push:
    branches:
      - master  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ec-2user/api
            git pull origin master
            shopt -s dotglob
            mv ./src/* .
            shopt -u dotglob
            rmdir ./src
            sudo rm -rf /usr/share/nginx/html
            sudo cp -r ./client/* /usr/share/nginx/html/
            rmdir ./client
            npm install
            pm2 restart api
            sudo systemctl restart nginx
          EOF
