name: Deploy to EC2

on:
  push:
    branches:
      - master  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo cd /home/ec2-user
            sudo git pull origin master
            sudo rm -rf /usr/share/nginx/html/
            sudo mkdir /usr/share/nginx/html/
            sudo cp -r ./client/* /usr/share/nginx/html/
            sudo cd api
            npm i
            pm2 restart server.js
            sudo systemctl restart nginx
          EOF
